#driver pack for WiFi adapters for android kernel by @D_L_NeroN
#
obj-y           += rtl8188eus/
obj-y           += rtl8812au/
obj-y           += rtl8188fu/
obj-y           += rtl8192eu/
obj-y           += mt7630/